solana-labs/networkexplorer

- .eslintrc.js
- api/api.js
- api/inbound-stream.js
- src/App.js
- src/App.test.js
- src/BxDialog.jsx
- src/index.js
> chore: React lint

- api/inbound-stream.js
(minor tweak for tick height adjustment)
> fix: minor tweak for tick_height outside entry

- api/api.js
- api/inbound-stream.js
- package.json
- src/App.js
- src/BxDataTable.jsx
- src/BxDialog.jsx
- src/BxDialogTransactions.jsx
- src/BxEntityLink.jsx
- src/BxStatsTable.jsx
- src/BxTransactionChart.jsx
- yarn.lock
* Transactions overall are too high-volume to watch
* We need a way to view transactions by program id (for example, tic-tac-toe)
* Todo: implement #12
* Introduce a txn-by-program-id topic per program id
* Make it easy to filter by account id on client- or server-side
> feat: view transactions by program id

- api/api.js
- src/App.css
- src/App.js
- src/BxDataTable.jsx
- src/BxDateTime.jsx
- src/BxDialog.jsx
- src/BxEntityLink.jsx
- src/BxHelpLink.jsx
- src/BxStatsTable.jsx
- src/BxTransactionChart.jsx
> feat: styling improvements

- api/inbound-stream.js
Prevents the blockexplorer api server from crashing when run against latest master.  
Root cause is that solana-web3.js is unable to deserialize the new Transaction binary format (cc: https://github.com/solana-labs/solana/issues/3681) so this patch is just a more graceful way to fail that will likely be exercised again in the future the next time the Transaction format changes
> fix: api server no longer crashes on empty transactions

- src/App.js
- src/BxStatsTable.jsx
- src/EndpointConfig.js
> feat: display cluster node count (requires solana v0.14.0)

- package.json
- src/BxAppBar.jsx
- src/BxDataTable.jsx
- src/BxDateTime.jsx
- src/BxDialog.jsx
- src/BxDialogTransactions.jsx
- src/BxEntityLink.jsx
- src/BxHelpLink.jsx
- src/BxStatsTable.jsx
- src/BxTransactionChart.jsx
Our beautifier was ignoring .jsx files 😱.  Not anymore!
> Pretty .jsx files

- api/api.js
- api/inbound-stream.js
- src/App.js
- src/BxDataTable.jsx
> WIP: account balance multi-get API

- api/inbound-stream.js
* Problem: redis overflowing memory on a 16GB fullnode with moderate load
* Solution: truncate objects (follow-up work will be more sustainable than dropping data)
* NOTE: Testing in progress
> WIP : feature : rough implementation of redis object expiration (128k timeline/6h object timeout)

- .eslintignore
- .travis.yml
- commitlint.config.js
- package.json
- yarn.lock
This will fail CI if semantic-release commit conventions are not used, to prevent accidental non-publishing of releases.
> ci: add commitlint

- api/api.js
- src/App.js
Problem:
* too many client-side RPC's
* tricky to navigate app logic
* tricky to manage refresh rates
Solution:
* consolidate work in the API server
* reduce client-side code
* place refresh rates in control of API server
> RFC: moving client-side logic into the API

- src/App.js
- src/index.js
- src/v2/Bx2EntityLink.jsx
- src/v2/Bx2PanelValidatorDetail.jsx
- src/v2/Bx2PanelValidators.jsx
Problem:
* need implementation of validator detail
Solution:
* implement validator detail page in v2
> feat: implement validator detail page

- src/v1/BxDialogWorldMap.jsx
cc: https://github.com/solana-labs/solana/pull/4918
cc: https://github.com/solana-labs/solana-web3.js/pull/390
> fix: commission is now a u8

- package.json
- src/App.js
- src/EndpointConfig.js
- src/index.js
- src/v1/BxAppBar.jsx
- src/v2/const.js
- yarn.lock
New UI is in the upper-right of the app:
> fix: make EndpointConfig dynamic and add v1 App UI to select different clusters

- src/EndpointConfig.js
Fixes https://github.com/solana-labs/solana/issues/4989
> fix: add testnet-tds to EndpointConfig map

- src/EndpointConfig.js
Freebie: fix: metrics url for tds cluster is now correct
> fix: switch to TLS endpoints

- src/AppV2.js
- src/v2/components/Footer/styles.js
- src/v2/components/NavBar/index.jsx
- src/v2/components/Validators/All/index.jsx
- src/v2/components/Validators/Detail/index.jsx
- src/v2/components/Validators/Detail/styles.js
- src/v2/components/Validators/Table/index.jsx
- src/v2/components/Validators/Table/styles.js
- src/v2/stores/nodes.js
@sunnygleason please review. this pr contains validator detail page and correction (mostly styling) for validators overview/list.
> feat: validators detail page and list page corrections

- package.json
- src/App.js
- src/v2/Bx2PanelTourDeSolLeaderboard.jsx
- yarn.lock
> feat: implementation of TdS leaderboard (pending additional fields)

- src/index.js
- src/v2/components/Header/index.jsx
- src/v2/components/Header/styles.js
- src/v2/components/HelpLink/index.jsx
- src/v2/components/HelpLink/styles.js
- src/v2/components/NavBar/assets/applications.svg
- src/v2/components/NavBar/index.jsx
- src/v2/components/NavBar/styles.js
- src/v2/components/ScrollToTop/index.jsx
- src/v2/components/Validators/Detail/index.jsx
- src/v2/components/Validators/Detail/styles.js
- src/v2/theme.js
header and menu icons has been updated and corrected
help link moved to separate component
scroll to top of page on menu navigation event
minor css styles
> fix: components and css corrections

- api/api.js
- package.json
- src/App.js
- src/v2/Bx2PanelTourDeSolLeaderboard.jsx
- src/v2/Bx2PanelValidatorDetail.jsx
- src/v2/Bx2PanelValidators.jsx
- src/v2/Bx2PanelValidatorsOverview.jsx
- src/v2/Bx2ValidatorIdentity.jsx
- yarn.lock
- add validator identity info to cluster info cache
- create validator identity component
- add validator identity info to all of the validator screens (list, overview, tds, detail)
- add avatar image
> feat: add validator identity info

- package.json
- public/index.html
- src/v2/components/Footer/Newsletter/index.jsx
- src/v2/components/Footer/Partnership/index.jsx
- src/v2/components/NavBar/index.jsx
- src/v2/components/Social/index.jsx
- src/v2/components/TourDeSol/Cards/index.jsx
- src/v2/components/TourDeSol/Ranking/index.jsx
- src/v2/components/Validators/Detail/index.jsx
- src/v2/components/Validators/index.jsx
- src/v2/mixpanel.js
- yarn.lock
+ one small change related to validators amount on tds page i forgot in previous pr :)
> feat: mixpanel and ga integration

- src/v2/components/NavBar/styles.js
- src/v2/components/Validators/styles.js
navigation and validators page small corrections.
> fix: qa feedback

- api/api.js
- src/App.js
- src/AppV2.js
- src/v2/components/Dashboard/NetworkOverview/index.jsx
- src/v2/components/Dashboard/NetworkOverview/styles.js
- src/v2/components/TourDeSol/Cards/index.jsx
- src/v2/components/UI/StatCard/index.jsx
- src/v2/components/Validators/Table/index.jsx
- src/v2/stores/nodes.js
- src/v2/utils/parseMessage.js
Notes:
* this changes wire protocol for cluster info (requires API/webapp to be in sync)
* adds "all" voting accounts from RPC endpoint
> feat: updates for TdS

- src/v2/components/Blocks/Detail/index.jsx
- src/v2/components/Blocks/Table/index.jsx
- src/v2/components/Dashboard/NetworkOverview/NodesMap/index.jsx
- src/v2/components/TourDeSol/Table/index.jsx
- src/v2/components/UI/Avatar/index.jsx
- src/v2/components/Validators/Detail/index.jsx
- src/v2/components/Validators/Table/index.jsx
https://app.asana.com/0/1132948208193741/1134085879486928/f
we don't need initials overlay over avatar with new design approach. it is either way keybase avatar or default pattern based avatar
> fix: rm validator initial from avatar pic

- src/v2/components/UI/CopyBtn/index.jsx
- src/v2/components/UI/CopyBtn/styles.js
- src/v2/components/Validators/Detail/index.jsx
https://app.asana.com/0/1132948208193741/1133753747733702
> fix: copy address cursor

- src/v2/components/Search/result.jsx
https://app.asana.com/0/1132948208193741/1133576441333044
> feat: track mixpanel search event

- api/api.js
- package.json
- src/App.js
- src/v2/components/Dashboard/NetworkOverview/NodesMap/index.jsx
- src/v2/components/Dashboard/NetworkOverview/StatCards/index.jsx
- src/v2/components/Dashboard/NetworkOverview/TPS/index.jsx
- src/v2/components/Footer/Partnership/index.jsx
- src/v2/components/NavBar/index.jsx
- src/v2/components/Search/index.jsx
- src/v2/components/Search/styles.js
- src/v2/components/Social/index.jsx
- src/v2/components/TourDeSol/Cards/index.jsx
- src/v2/components/TourDeSol/Cards/styles.js
- src/v2/components/TourDeSol/Stage.jsx
- src/v2/components/TourDeSol/Table/index.jsx
- src/v2/components/TourDeSol/index.jsx
- src/v2/components/TourDeSol/styles.js
- src/v2/components/UI/Loader/index.jsx
- src/v2/components/UI/StatCard/styles.js
- src/v2/components/Validators/Table/index.jsx
- src/v2/components/Validators/index.jsx
- src/v2/components/Validators/styles.js
- src/v2/constants.js
- src/v2/stores/networkOverview.js
- src/v2/stores/nodes.js
- src/v2/utils/insertIf.js
- yarn.lock
Fixes #293 
Fixes #308
Fixes #295 
Fixes #302 
Fixes #303 
Fixes #307 
Fixes #304 
Fixes #296 
Fixes #306 
Fixes #310 
Fixes #305 
Fixes #294 
Fixes #292 
Fixes #290 
Fixes #286
> fix: qa issues

- src/v2/components/TourDeSol/Ranking/styles.js
> fix: long name advantage

- src/v2/components/Validators/Detail/index.jsx
https://app.asana.com/0/1132948208193741/1137402346204877
> detail page updated with amount of delegated sol

- src/v2/components/Dashboard/NetworkOverview/StatCards/styles.js
Fixes #343 
@CriesofCarrots i still can't see it but i hope this helps.
> fix: introduce line height

- src/v2/components/Dashboard/NetworkOverview/StatCards/styles.js
- src/v2/components/TourDeSol/Stage.jsx
temporarily stage dates replaced with coming soon message
minor css stats card correction
Fixes #293
> fix: stages are coming soon

- src/v2/components/TourDeSol/Cards/index.jsx
- src/v2/components/TourDeSol/Table/index.jsx
- src/v2/components/Validators/All/index.jsx
- src/v2/components/Validators/Table/index.jsx
- src/v2/stores/nodes.js
> fix: default validators store method returns all validators

- src/v2/components/Search/index.jsx
- src/v2/components/Search/result.jsx
- src/v2/components/Search/styles.js
- src/v2/components/TourDeSol/Cards/index.jsx
- src/v2/components/TourDeSol/Table/index.jsx
- src/v2/components/Validators/All/index.jsx
- src/v2/components/Validators/Table/index.jsx
- src/v2/stores/nodes.js
> fix: search results based on searching term

- src/v2/components/Search/index.jsx
Problem:
* minor nit w/ code duplication makes it hard to understand (reduce)
Solution:
* slightly restructure the search function (compact/map)
> fix: reduce duplication in search function

- src/AppV2.js
- src/v2/@types/table.js
- src/v2/components/Applications/Table/index.jsx
- src/v2/components/Blocks/Table/index.jsx
- src/v2/components/Favorites/Accounts.jsx
- src/v2/components/Favorites/index.jsx
- src/v2/components/Favorites/styles.js
- src/v2/components/Transactions/Table/index.jsx
> feat: favs tab

- api/api.js
- api/fullnode-url.js
- api/inbound-stream.js
- api/loaders/blocks/detail.js
- api/loaders/blocks/index.js
- api/loaders/timeline.js
- api/loaders/transactions/detail.js
- api/loaders/transactions/index.js
- api/network-explorer.js
- api/uptime-crawler.js
- api/util.js
- api/views/blocks/detail.js
- api/views/blocks/index.js
- api/views/transactions/detail.js
- api/views/transactions/index.js
Problem:
* we need backends for Blocks and Transactions pages that support pagination
* we need better encapsulation of data retrieval from redis and formatting for output
Solution:
* implement `loaders` with pagination to encapsulate retrieving raw data from redis
* implement `views` to encapsulate formatting of data for display in network explorer
Next Steps:
* hook up backend to frontend
* enable `refresh` functionality
* implement similar functionality for Applications (and validators?)
> blocks and transaction backends

- package.json
Problem:
* recursive directories weren't getting picked up by the build step
Solution:
* use the magic babel incantation
> fix: we <3 recursive directory structure

- api/loaders/blocks/index.js
- api/loaders/parseMessage.js
- api/loaders/transactions/index.js
- package.json
Problem:
* previous fix adds recursion but misses the api directory
Solution:
* reinstate the api directory
> Hotfix: build:api target needs to create subdirectory

- api/loaders/parseMessage.js
- api/loaders/timeline.js
- api/loaders/transactions/index.js
- api/network-explorer.js
- api/views/blocks/index.js
- api/views/transactions/index.js
- src/AppV2.js
- src/v2/api/blocks.js
- src/v2/api/transactions.js
- src/v2/components/Blocks/Detail/index.jsx
- src/v2/components/Blocks/Detail/styles.js
- src/v2/components/Blocks/Table/index.jsx
- src/v2/components/Blocks/Table/styles.js
- src/v2/components/Blocks/index.jsx
- src/v2/components/Blocks/styles.js
- src/v2/components/HelpLink/index.jsx
- src/v2/components/Transactions/Detail/Application/index.jsx
- src/v2/components/Transactions/Detail/ApplicationsTab.jsx
- src/v2/components/Transactions/Detail/Code/index.jsx
- src/v2/components/Transactions/Detail/Code/styles.js
- src/v2/components/Transactions/Detail/Status/index.jsx
- src/v2/components/Transactions/Detail/index.jsx
- src/v2/components/Transactions/Table/index.jsx
- src/v2/components/Transactions/index.jsx
- src/v2/stores/blocks/detail.js
- src/v2/stores/blocks/timeline.js
- src/v2/stores/transactions/detail.js
- src/v2/stores/transactions/timeline.js
Problem:
* current blocks and transaction views are just mockups
Solution:
* implementation of blocks and transaction views
> feat: transaction & blocks timeline & detail views

- api/network-explorer.js
- api/views/blocks/detail.js
- api/views/blocks/index.js
- api/views/transactions/detail.js
- api/views/transactions/index.js
Problem:
* there are "silent hangs" when redis doesn't return correctly
Solution (round 1):
* at the top level, use a FriendlyGet and provide for error returns
(This is to help debug current deployment; In future rounds,
there is more error handling we can/will do)...
> feat: improve error handling in new APIs

- package.json
- yarn.lock
Problem:
* inflation API changed upstream
Solution:
* bump web3js version
> fix: bump web3js version

- src/v2/components/Validators/Detail/index.jsx
> feat: add uptime to validator detail

- api/api.js
- api/inbound-stream.js
- api/loaders/applications/detail.js
- api/loaders/applications/index.js
- api/loaders/applications/recency.js
- api/network-explorer.js
- api/views/applications/detail.js
- api/views/applications/index.js
- src/v2/api/applications.js
- src/v2/components/Applications/Detail/Code/index.jsx
- src/v2/components/Applications/Detail/Details/index.jsx
- src/v2/components/Applications/Detail/index.jsx
- src/v2/components/Applications/Detail/styles.js
- src/v2/components/Applications/Table/index.jsx
- src/v2/components/Applications/index.jsx
- src/v2/components/Transactions/Detail/Application/index.jsx
- src/v2/components/Transactions/Detail/Application/styles.js
- src/v2/stores/applications/detail.js
- src/v2/stores/applications/timeline.js
Problem:
* application index & detail pages aren't implemented
Solution:
* implement application index & detail API's and connect to frontend
Still TODO:
* figure out heuristic to create "labels" for programs ("other", "system", "consensus" etc)
> Application index & detail pages

- src/v2/components/Footer/Partnership/index.jsx
> fix: links corrected with providing target and rel attr

- src/v2/components/Footer/Partnership/Disclaimer.jsx
- src/v2/components/Footer/Partnership/index.jsx
- src/v2/components/Footer/Partnership/styles.js
- src/v2/components/UI/SectionHeader/styles.js
> feat: disclaimer

- src/v2/utils/getUptime.js
> fix: uptime overflow

- package.json
- src/AppV2.js
- src/v2/components/TourDeSol/index.jsx
- src/v2/components/UI/CopyBtn/index.jsx
- yarn.lock
> action bars

- src/v2/components/Dashboard/NetworkOverview/StatCards/index.jsx
- src/v2/components/Dashboard/NetworkOverview/StatCards/styles.js
- src/v2/components/UI/StatCard/index.jsx
- src/v2/components/UI/StatCard/styles.js
> feat: tooltips on stats cards hover

- src/v2/components/Transactions/Detail/Application/index.jsx
- src/v2/components/Transactions/Detail/Application/styles.js
- src/v2/components/Transactions/Table/index.jsx
- src/v2/components/Transactions/index.jsx
- src/v2/components/Transactions/styles.js
> fix: tx pagination styling

- src/v2/components/Validators/index.jsx
> fix: hide static timestamp until we decide actual format

- src/v2/components/Validators/Detail/index.jsx
> fix: commission format on detail page

- src/v2/components/Validators/Table/index.jsx
- src/v2/components/Validators/Table/styles.js
> fix: loading animation on validators table

- src/v2/components/Validators/Table/index.jsx
> fix: add tooltips to validators table columns

- src/v2/components/UI/Table/index.jsx
- src/v2/components/UI/Table/styles.js
- src/v2/components/Validators/Table/index.jsx
- src/v2/components/Validators/Table/styles.js
> feat: validators sorting table

- src/v2/components/ValidatorsMap/Marker.jsx
> fix: map marker scaling

- src/AppV2.js
- src/v2/components/Account/Detail/Chart/index.jsx
- src/v2/components/Account/Detail/Chart/styles.js
- src/v2/components/Account/Detail/Code/index.jsx
- src/v2/components/Account/Detail/Code/styles.js
- src/v2/components/Account/Detail/Transactions/index.jsx
- src/v2/components/Account/Detail/Transactions/styles.js
- src/v2/components/Account/Detail/index.jsx
- src/v2/components/Account/Detail/styles.js
- src/v2/components/HelpLink/styles.js
- src/v2/components/Transactions/Detail/Application/index.jsx
- src/v2/components/Transactions/Detail/Application/styles.js
> feat: account details page

- package.json
- src/v1/BxDialogWorldMap.jsx
Match solana->solana-web3.js changes: https://github.com/solana-labs/solana-web3.js/pull/524
(Will need solana-web3 version bump)
> fix: update fullnodeExit to validatorExit

- package.json
- yarn.lock
PROBLEM:
* `api` server isn't getting vote account info b/c of client response validation `rootSlot`
SOLUTION:
* (bump)
> feat: bump solana client for rootSlot fix

- src/v2/stores/nodes.js
> fix: map markers are back

- src/v2/components/Dashboard/NetworkOverview/StatCards/styles.js
> fix: no wrap public key

- src/v2/components/Validators/Table/index.jsx
> fix: table values format

- src/v2/components/Validators/Table/styles.js
> fix: font size consistency

- src/v2/components/TourDeSol/Table/index.jsx
- src/v2/components/TourDeSol/index.jsx
> fix: better table and values styles

- api/views/tourdesol/index.js
- src/v2/components/TourDeSol/Table/index.jsx
PROBLEM:
* avoid computation of attributes in view
* prefer formatting of attributes in view
* need to robustify object access in case attributes aren't there (hi, keybase attrs! 👋)
SOLUTION:
* compute in API
* format in display
* robustify access
> feat: compute in api, format in display, plus robustify access

- api/api.js
PROBLEM:
* too many geoip calls 💸 
SOLUTION:
* redis all the things 💰
> feat: implement 2d redis geoip cache

- src/v2/components/Accounts/Table/index.jsx
- src/v2/components/Blocks/Table/index.jsx
- src/v2/components/Blocks/Table/styles.js
- src/v2/components/HelpLink/index.jsx
- src/v2/components/Programs/Table/index.jsx
- src/v2/components/Programs/Table/styles.js
- src/v2/components/Transactions/Table/index.jsx
- src/v2/components/UI/TabNav/index.jsx
- src/v2/components/UI/TableCard/index.jsx
- src/v2/components/UI/TableCard/styles.js
- src/v2/components/Validators/Detail/index.jsx
- src/v2/components/Validators/Table/index.jsx
- src/v2/stores/nodes.js
mobile table render incapsulated in separate component
some values calculation moved to store
> fix: mobile tables refactored

- src/v2/stores/nodes.js
quick validation of coordinates. will rm as soon as api will be fixed.
> fix: coords validation

- api/fullnode-url.js
- api/loaders/tourdesol/index.js
- api/uptime-crawler.js
- api/util.js
- api/views/tourdesol/index.js
- src/v2/components/TourDeSol/Table/index.jsx
- src/v2/components/ValidatorsMap/Marker.jsx
PROBLEM:
* we were using hard-coded slots_per_epoch
SOLUTION:
* use the new getEpochSchedule API
> feat: use epoch schedule for uptime calculation

- api/util.js
- api/views/tourdesol/index.js
- src/v2/components/TourDeSol/Table/index.jsx
- src/v2/components/UI/Uptime/index.jsx
- src/v2/components/UI/Uptime/styles.js
- src/v2/components/UI/ValidatorName/index.jsx
PROBLEM:
* uptime calculation is a little gnarly 🏄 
* we're not exposing all the information about uptime calculation ℹ️ 
SOLUTION:
* make a component so we can provide improved uptime display 🕐 
TODO (subsequent PR):
* refactor Validator page to use this improved view 🚧
> Improved uptime

- api/api.js
- api/util.js
- api/views/accounts/detail.js
- api/views/programs/detail.js
- api/views/tourdesol/index.js
- src/v2/components/Validators/index.jsx
- src/v2/constants.js
- src/v2/stores/accounts/detail.js
- src/v2/stores/nodes.js
- src/v2/stores/programs/detail.js
PROBLEM:
* looks like the ratio might be changing? https://github.com/solana-labs/solana-web3.js/pull/541
SOLUTION:
* I did a quick check for usage, looks like not a ton of places
* tentative PR for if/when PR 541 goes through
> RFC: update lamports per sol?

- src/v2/components/NavBar/index.jsx
Proposal:
* add accounts index link to Nav Bar
* (if approved, we'll need an account icon as well, this is just a placeholder)
> Add accounts index link to NavBar

- src/v2/components/TourDeSol/Stage.jsx
> fix: TdS stage 'finished soon' -> 'finished' (fixes #565)

- api/util.js
(fix needed for https://github.com/solana-labs/solana-web3.js/pull/594)
> feat: use new LAMPORTS_PER_SOL constant

- api/api.js
- src/v1/BxDialogWorldMap.jsx
- src/v2/components/Validators/Detail/index.jsx
- src/v2/components/Validators/index.jsx
(fixed via personal request from @CriesofCarrots )
> feat: fix commision (0-100) and staked sol (handle null/NaN)
