solana-labs/networkexplorer

api/config.js
Required by solana-labs/solana#2857 for testnet deployment
=> fix: rename entry-stream to blockstream

README.md, api/api.js, api/config.js, api/inbound-stream.js
As we get ready for performance/scale testing, we're leaving
performance on the table with our current localhost TCP socket
integration between api.js, inbound-stream.js and the local redis
server.
Add Unix Domain Socket integration for this higher-performance
use case, so that as we begin scale testing, we're using the highest
performing option available.
=> feat: add redis Unix Domain Socket support for high performance

api/inbound-stream.js
To catch up with solana core, need to update entry.id to entry.hash, renamed here: https://github.com/solana-labs/solana/commit/7c4473e0aabcd4e781f092146f1d7ec2967ace33
=> Update entry.id to entry.hash

bin/blockexplorer.sh, package.json, yarn.lock
When we started using `await` in api.js, we inadvertently added a dependency on `babel-plugin-transform-runtime` that is only visible in the deployed blockexplorer since we use `babel-node` in development
=> fix: add babel-plugin-transform-runtime to resolve api server start failure

.env.production
Sorry @manuel-calavera, `REACT_APP_BASE_URL` just needs to be removed.   This is just a hack in the meantime to unbreak the production build.
https://github.com/solana-labs/blockexplorer/blob/master/src/v2/api/socket.js needs a rework such that it doesn't hard code its URL.   The ws/wss URL should come from EndpointConfig.js, and it can change at runtime.
=> fix: hack up .env.production to avoid breaking production builds

api/api.js
problem:
* blockexplorer UI calculates total bonded tokens
* this should be calculated from an API
solution:
* place calculation into the JS API (for now)
=> feat: total bonded tokens in cluster-info API response

src/App.js
I noticed some console errors when connecting to the beta testnet on the latest explorer. This should fix those errors.
=> fix: support cluster-info responses without identity and uptime data

src/v2/components/TourDeSol/Cards/index.jsx, src/v2/components/TourDeSol/index.jsx
Problem:
* we don't have dynamic configuration of active TdS stage
* we don't have data regarding TdS stage length/start dates/etc
* TdS stat cards are TODO for block duration, days left, etc
Solution:
* implement an environment variable TDS_ACTIVE_STAGE taking a value (0-3+)
* if value is 0, all stages are "coming" + start date
* if value is [1-3], active stage is highlighted, stages are 'coming' or 'finished'
* if value is [4+], stages are 'finished'
* durations & dates are configurable in the source code
=> feat: TdS stage info & dynamic config

src/v2/components/Validators/Detail/index.jsx
@sunnygleason / @manuel-calavera - not sure if you guys rather push this logic down a layer into the store or even API server though, as this calculation may surface elsewhere in the UI too?
=> fix: correctly map commision field to %

api/api.js, api/uptime-crawler.js, src/v2/components/Dashboard/NetworkOverview/StatCards/index.jsx, src/v2/components/TourDeSol/Cards/index.jsx, src/v2/components/TourDeSol/Table/index.jsx, src/v2/components/TourDeSol/index.jsx, src/v2/components/Validators/All/index.jsx, src/v2/components/Validators/Detail/index.jsx, src/v2/components/Validators/Table/index.jsx, src/v2/components/Validators/index.jsx, src/v2/stores/nodes.js, src/v2/utils/parseMessage.js
problem:
* the validators list is more confusing than necessary because there isn't a "real" API for it
* we currently have to do a complicated "merge" between cluster gossip, epoch vote info and all vote account info
solution:
* we'd like this logic to move closer to the fullnode
* currently, we'll settle for moving it into the JS api
Upcoming PR: migrating validator display to this data model
=> feat: more canonical data from API

api/uptime-crawler.js, package.json, yarn.lock
Problem:
* uptime *used* to require solana CLI and way too much forking
Solution:
* use the shiny web3js functionality instead
=> feat: remove command-line solana dep, use web3js for uptime instead

api/api.js
Problem:
* inflation info is static/hard-coded in the JS API
Solution:
* use the new `getInflation()` RPC to retrieve the inflation parameters
NOTE: don't merge this until we have newer v0.18 builds (everywhere)
=> feat: derive networkInflationRate from fullnode getInflation() RPC

package.json, src/v2/components/TourDeSol/index.jsx
Problem:
* we'd like to be able to see TdS-style ranking when TdS network is unavailable
Solution:
* add a "force=true" query parameter to force display of the TdS page
=> feat: add force=true parameter to force TdS page display

api/api.js
Problem:
* icky usernames are failing the whole batch Keybase lookup
Solution:
* sanitize keybase usernames (imperfect but at least a first line of defense)
=> fix: sanitize usernames

src/v2/stores/nodes.js
=> fix: marker showing pubkey if no name specified

api/loaders/tourdesol/index.js, api/network-explorer.js, api/util.js, api/views/tourdesol/index.js, src/v2/api/tourdesol.js, src/v2/components/TourDeSol/Cards/index.jsx, src/v2/components/TourDeSol/Ranking/index.jsx, src/v2/components/TourDeSol/Stage.jsx, src/v2/components/TourDeSol/Table/index.jsx, src/v2/components/TourDeSol/index.jsx, src/v2/constants.js, src/v2/stores/tourdesol/index.js
Problem:
* the current bikes don't race 😞 
Solution:
* implement the race position function as: `blockBasedPosition + stakeBasedAdjustment` 🚲 
* since it's so hard to test, put in a demo mode for the meantime so folks can check out the mechanics 🐎
=> feat: tds scoring and api implementation

api/friendlyGet.js
PROBLEM:
* error data structure can apparently be circular sometimes 🌎 
SOLUTION:
* use `util.inspect` instead of `JSON.stringify` to flatten things out 💌
=> feat: better error messages by using util.inspect

src/v2/components/Dashboard/NetworkOverview/StatCards/index.jsx, src/v2/stores/nodes.js
PROBLEM:
* white screen on beta explorer, seems related to map markers
* react warning on tooltip - title attribute not provided
SOLUTION:
* robustify map marker computation
* provide default empty string for tooltip
=> feat: handle mapmarker errors, empty leader tooltip

src/v2/components/NavBar/index.jsx
enabled blocks and transactions tabs and regrouped them a little. programs tab does not show anything and still need to be styled so i kept it disabled. favs also disabled for now
=> feat: enable blocks and transactions tabs

api/api.js
with new geo solution coords are strings and as result an issue with concatenation of string and number produces next invalid result:
(-26.04450-0.00937225796214989, 28.01870-0.01101979164350269)
Fix is to convert to number coords.
=> fix: offset adding

src/v2/components/Accounts/Table/index.jsx, src/v2/components/Accounts/index.jsx, src/v2/components/Blocks/Table/index.jsx, src/v2/components/Blocks/index.jsx, src/v2/components/Programs/Table/index.jsx, src/v2/components/Programs/index.jsx, src/v2/components/Transactions/Detail/index.jsx, src/v2/components/Transactions/Table/index.jsx, src/v2/components/Transactions/index.jsx, src/v2/components/UI/TableNav/index.jsx
PROBLEM:
* program index page broken, should be `programId` 💔 
* program index page should have "last called" timestamp because it's useful for debugging 🕐 
* table navigation broken `next`/`prev` 🚢 
* any timestamp should have actual timestamp mouseover ⌚️ 
SOLUTION:
* fix `programId` 🔧 
* put back `last called` 🕐 
* fix `next`/`prev` 🚗 
* add timestamps ⌚️
=> fixing up a few things

src/v2/components/UI/Avatar/index.jsx
Problem
* a recent version of material-ui includes a fallback icon for Avatar
Solution
* pass an "empty child" node to disable fallback icon
=> feat: diable @material-ui Avatar fallback icon
